// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBde1k77JkckkZQ14dQjviru2knc170I08',
    appId: '1:572241987462:web:a495af106618bf6d85ce07',
    messagingSenderId: '572241987462',
    projectId: 'quadleo-project',
    authDomain: 'quadleo-project.firebaseapp.com',
    storageBucket: 'quadleo-project.firebasestorage.app',
    measurementId: 'G-H1ZHT5SNX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywjQ0zkA4MEn_n3U0_A_G8SI6DdOlJpQ',
    appId: '1:572241987462:android:37f6cabfd002b3f085ce07',
    messagingSenderId: '572241987462',
    projectId: 'quadleo-project',
    storageBucket: 'quadleo-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OkFwC6rdAhoVN9gFGoWEJ6HYtR-JgCI',
    appId: '1:572241987462:ios:22b21ec148c247e885ce07',
    messagingSenderId: '572241987462',
    projectId: 'quadleo-project',
    storageBucket: 'quadleo-project.firebasestorage.app',
    iosBundleId: 'com.example.quadleoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8OkFwC6rdAhoVN9gFGoWEJ6HYtR-JgCI',
    appId: '1:572241987462:ios:22b21ec148c247e885ce07',
    messagingSenderId: '572241987462',
    projectId: 'quadleo-project',
    storageBucket: 'quadleo-project.firebasestorage.app',
    iosBundleId: 'com.example.quadleoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBde1k77JkckkZQ14dQjviru2knc170I08',
    appId: '1:572241987462:web:051fe67189dde07b85ce07',
    messagingSenderId: '572241987462',
    projectId: 'quadleo-project',
    authDomain: 'quadleo-project.firebaseapp.com',
    storageBucket: 'quadleo-project.firebasestorage.app',
    measurementId: 'G-0FW3DYZF7D',
  );
}
